name: Build and Deploy Docker Image

on:
  push:
    tags:
      - '*'
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ github.event.repository.name }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  auto-deploy-docker-job:
     needs: build-docker-image
     runs-on: ubuntu-latest
     env:
       SERVER_IP: ${{secrets.SERVER_IP}}
       SERVER_USERNAME: ${{secrets.SERVER_USERNAME}}
       SERVER_PASSWORD: ${{secrets.SERVER_PASSWORD}}
       CONTAINER_NAME: ${{github.actor}}
       SERVER_PORT: 9022
       DOCKER_IMAGE_URL: 'ghcr.io/${{ github.repository }}:${{ github.ref_name }}'
     steps:
      - name: Execute deployment script
        uses: appleboy/ssh-action@v1.2.3
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USERNAME }}
          password: ${{ env.SERVER_PASSWORD }}
          port: '22'
          script: |
            docker -V
            docker logout ghcr.io
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker rm -f ${{ env.CONTAINER_NAME }} || true
            docker pull ${{ env.DOCKER_IMAGE_URL }}
            docker run -d --name ${{ env.CONTAINER_NAME }} -p ${{ env.SERVER_PORT }}:80 ${{ env.DOCKER_IMAGE_URL }}