name: Deploy Frontend Workshop App
on:
  push:
    # branches:
    #   - main
    tags:
      - '*.*.*'
jobs:
  build-prod-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "build-prod-job works!"
  auto-deploy-job:
    runs-on: ubuntu-latest
    needs: build-prod-job
    steps:
      - run: echo "auto-deploy-job works!"