name: Deploy Frontend Workshop App
on:
  push:
    # branches:
    #   - main
    tags:
      - '*.*.*'
jobs:
  build-prod-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: echo "Hello, World!"
      - name: set up Node.js to use version 24.x
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        
      - name: run build production
        run: npm run build
      - name: upload production build artifacts
        uses: actions/upload-artifact@v5
        with:
          name: dist-production
          path: dist
  auto-deploy-job:
    runs-on: ubuntu-latest
    needs: build-prod-job
    steps:
      - name: download production build artifacts
        uses: actions/download-artifact@v6
        with:
          name: dist-production
          path: dist
      - run: ls dist
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist